### ISSUE TITLE
Implementation questions

### ISSUE THREAD

**Issue by dwightjack** [egoist/revue#2]
Hi,

I was actually looking into vue + redux implementation then I saw you where already working on it.

I have a couple of questions about the implementation. Some of them could be related to my relative knowledge on Vue internals:

## 1) `defineReactive`

You are using `defineReactive` to attach revue methods to the Vue prototype, but it seems to me that that utility is mainly used to implement reactive setters/getters on data props. I think that using it on revue methods/props could be useful just to react to store binding changes:

```
this.$revue = otherReduxStore;
```

## 2) object data props

When using objects as data props (like the todo array in the example), they got deeply enhanced by Vue's  observer. This ends up altering the plain objects on the redux state. While it's not an issue i was wondering if there would be side effects using the same store on 2 different Vue apps coexisting in the same page.

## 3) ChangeHandler

Using `previousValue !== currentValue` to check for value changes is fine for native values, but for objects and arrays always returns `true` thus triggering the observer on Vue instance.

Sorry for the long post :) and thanks in advance!

**Comment by egoist** [comment]
Definitely gotcha.

1) fixed with Object.defineProperties
2) what you mean 「2 different Vue apps」? if you mean 2 different Vue instances, they won't affect each other.
3) still working on this.

**Comment by dwightjack** [comment]
Hi,

Thanks for replying and for the clarifications.
Abouy 2) I was meaning 2 different instances, yes, so that's fine. About 3) you could use [shallowequal](https://www.npmjs.com/package/shallowequal).It's not deep, so array of objects will still return false, but it's faster then _.isEqual. I'm not sure which is a better option in the scope of a Vue application average data size.

**Comment by egoist** [comment]
now using shallowEqual

**Comment by dwightjack** [comment]
Cool! Thanks!

**Comment by egoist** [comment]
update:

about 2) if you do return a new state instead of modify it directly in reducers, it won't have side effect.

**Comment by dwightjack** [comment]
Thanks, if I understand well, in this discussion  (http://forum.vuejs.org/topic/102/does-vue-benefit-from-this-approach-redux/9) also Evan agrees it won't cause side effects.
I tried to cite you but couldn't find your nickname :)
